FROM python:3.11-slim

# Create working directory
WORKDIR /app

# Install MLflow
RUN pip install mlflow==3.10

# Copy experiment data into container
COPY mlruns /app/mlruns

# Set environment variable for MLflow tracking URI
ENV MLFLOW_TRACKING_URI=file:///app/mlruns

# Expose MLflow default port
EXPOSE 5000

# Start MLflow UI
CMD ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]