FROM python:3.11-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos necesarios
COPY . .

# Instalar MLflow
RUN pip install --no-cache-dir mlflow

# Exponer el puerto en el que corre MLflow UI
EXPOSE 5000

# Ejecutar MLflow UI al iniciar el contenedor
CMD ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]
